### ISSUE TITLE
Forums Can't Have Register/Login.

### ISSUE THREAD

**Issue by bjskistad** [Newawe/Newawe-Forums#2]
The forums can't have their own login and register. We need them to be already logged in to use the forums. We could use cookies... I think.

**Comment by Radical-from-Scratch** [comment]
Well, they're gonna *have* them, I just need to make some modifications.

**Comment by bjskistad** [comment]
It'll need to be connected to their regular account.

**Comment by Radical-from-Scratch** [comment]
That is what I meant.

**Comment by bjskistad** [comment]
K
