### ISSUE TITLE
We need to add reCAPTCHA or any other CAPTCHA to prevent spammers

### ISSUE THREAD

**Issue by DrKat123** [Newawe/newawe-forums#4]
Whoops, i put too much in the title :stuck_out_tongue: 
title explains all

**Comment by bjskistad** [comment]
This would be needed for general registration. :P

**Comment by DrKat123** [comment]
yep

where is the forums hosted in?

i need it to add recaptcha

**Comment by bjskistad** [comment]
Huh? The forums hosted in? I don't understand.

**Comment by Radical-from-Scratch** [comment]
The forums will be linked to the main registration, so people won't be registering in the forums at all

**Comment by DrKat123** [comment]
where's the URI for the forums? (eg. mydomain.com/forums)

**Comment by DrKat123** [comment]
Ninja'd

**Comment by Radical-from-Scratch** [comment]
Currently, they are at http://newawe.gwiddle.co.uk/Fourm, but they will be moving soon.

**Comment by bjskistad** [comment]
This is still an issue, just in the main repo. I'll add it there.

**Comment by Radical-from-Scratch** [comment]
zk

**Comment by bjskistad** [comment]
:P You misspelled. #grammarpolice
